// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_banThucPhamSach.Data;

#nullable disable

namespace Web_banThucPhamSach.Migrations
{
    [DbContext(typeof(WebBanThucPhamSachContext))]
    [Migration("20241013160718_UpdateOrderTable")]
    partial class UpdateOrderTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_banThucPhamSach.Data.Cart", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<double?>("AllTotal")
                        .HasColumnType("float")
                        .HasColumnName("allTotal");

                    b.Property<int?>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<string>("ProductId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("UserId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Cart__3213E83F5DBB4CE7");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Category__3213E83F32124B4C");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Feedback", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fullname");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Feedback__3213E83F34BC4EC7");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image");

                    b.Property<string>("ProductId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("PK__Gallery__3213E83FB9026C00");

                    b.HasIndex("ProductId");

                    b.ToTable("Gallery", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.InputWarehouse", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DateIn")
                        .HasColumnType("datetime")
                        .HasColumnName("dateIn");

                    b.Property<string>("NameProduct")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nameProduct");

                    b.Property<int?>("NumberInput")
                        .HasColumnType("int")
                        .HasColumnName("numberInput");

                    b.Property<string>("ProductId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("product_id");

                    b.Property<string>("SuppliersId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("suppliers_id");

                    b.Property<double?>("Total")
                        .HasColumnType("float")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PK__InputWar__3213E83F8D515E03");

                    b.HasIndex("ProductId");

                    b.HasIndex("SuppliersId");

                    b.ToTable("InputWarehouse", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.NewsletterSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("SubscribeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("subscribe_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Newslett__3213E83FAC7526A9");

                    b.HasIndex("UserId");

                    b.ToTable("NewsletterSubscription", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fullname");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("order_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<double?>("TotalMoney")
                        .HasColumnType("float")
                        .HasColumnName("total_money");

                    b.HasKey("Id")
                        .HasName("PK__Order__3213E83F8A0614B7");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.OrderDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<double?>("Discount")
                        .HasColumnType("float")
                        .HasColumnName("discount");

                    b.Property<int?>("NumberProducts")
                        .HasColumnType("int")
                        .HasColumnName("number_products");

                    b.Property<string>("OrderId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("order_id");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<string>("ProductId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("product_id");

                    b.Property<string>("PromotionId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("promotion_id");

                    b.Property<double?>("TotalMoney")
                        .HasColumnType("float")
                        .HasColumnName("total_money");

                    b.HasKey("Id")
                        .HasName("PK__OrderDet__3213E83FC494DA14");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PromotionId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.OrderHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ChangeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("change_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("OrderId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__OrderHis__3213E83F7EAC01A3");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderHistory", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.PaymentOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OrderId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("order_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_status");

                    b.Property<double?>("TotalAmount")
                        .HasColumnType("float")
                        .HasColumnName("total_amount");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("PK__PaymentO__3213E83FEE429334");

                    b.HasIndex("OrderId");

                    b.ToTable("PaymentOptions");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionDish")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_dish");

                    b.Property<double?>("Discount")
                        .HasColumnType("float")
                        .HasColumnName("discount");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Product__3213E83FE12EAD7B");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Promotion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<double?>("DiscountPercentage")
                        .HasColumnType("float")
                        .HasColumnName("discount_percentage");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("ProductId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Promotio__3213E83FA6CE7E43");

                    b.HasIndex("ProductId");

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ProductId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Review__3213E83F4A1D66F0");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Role__3213E83FFF252E8C");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Shipping", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("OrderId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("order_id");

                    b.Property<double?>("ShippingFee")
                        .HasColumnType("float")
                        .HasColumnName("shipping_fee");

                    b.Property<string>("ShippingMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("shipping_method");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("tracking_number");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Shipping__3213E83F3E78312C");

                    b.HasIndex("OrderId");

                    b.ToTable("Shipping", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Staff", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fullName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__staff__3213E83F8F2ABAD2");

                    b.HasIndex("RoleId");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Supplier", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("phoneNumber");

                    b.HasKey("Id")
                        .HasName("PK__Supplier__3213E83FE196FB35");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fullname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("PK__User__3213E83FA966300D");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Warehouse", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("id");

                    b.Property<string>("InputWarehoseId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("inputWarehose_id");

                    b.Property<int?>("NumberProduct")
                        .HasColumnType("int")
                        .HasColumnName("number_product");

                    b.HasKey("Id")
                        .HasName("PK__Warehous__3213E83F2451DF4C");

                    b.HasIndex("InputWarehoseId");

                    b.ToTable("Warehouse", (string)null);
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Cart", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Cart__product_id__787EE5A0");

                    b.HasOne("Web_banThucPhamSach.Data.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Cart__user_id__797309D9");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Feedback", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Feedback__user_i__22AA2996");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Gallery", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.Product", "Product")
                        .WithMany("Galleries")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Gallery__product__1DE57479");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.InputWarehouse", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.Product", "Product")
                        .WithMany("InputWarehouses")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__InputWare__produ__71D1E811");

                    b.HasOne("Web_banThucPhamSach.Data.Supplier", "Suppliers")
                        .WithMany("InputWarehouses")
                        .HasForeignKey("SuppliersId")
                        .HasConstraintName("FK__InputWare__suppl__72C60C4A");

                    b.Navigation("Product");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.NewsletterSubscription", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.User", "User")
                        .WithMany("NewsletterSubscriptions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Newslette__user___440B1D61");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.OrderDetail", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__OrderDeta__order__2D27B809");

                    b.HasOne("Web_banThucPhamSach.Data.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__OrderDeta__produ__2F10007B");

                    b.HasOne("Web_banThucPhamSach.Data.Promotion", "Promotion")
                        .WithMany("OrderDetails")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK__OrderDeta__promo__2E1BDC42");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.OrderHistory", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.Order", "Order")
                        .WithMany("OrderHistories")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__OrderHist__order__3D5E1FD2");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.PaymentOption", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.Order", "Order")
                        .WithMany("PaymentOptions")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__PaymentOp__order__403A8C7D");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Product", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Product__categor__1B0907CE");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Promotion", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Promotion__produ__2A4B4B5E");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Review", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Review__product___33D4B598");

                    b.HasOne("Web_banThucPhamSach.Data.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Review__user_id__34C8D9D1");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Shipping", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.Order", "Order")
                        .WithMany("Shippings")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Shipping__order___398D8EEE");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Staff", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.Role", "Role")
                        .WithMany("Staff")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__staff__role_id__17F790F9");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.User", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__User__role_id__145C0A3F");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Warehouse", b =>
                {
                    b.HasOne("Web_banThucPhamSach.Data.InputWarehouse", "InputWarehose")
                        .WithMany("Warehouses")
                        .HasForeignKey("InputWarehoseId")
                        .HasConstraintName("FK__Warehouse__input__75A278F5");

                    b.Navigation("InputWarehose");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.InputWarehouse", b =>
                {
                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderHistories");

                    b.Navigation("PaymentOptions");

                    b.Navigation("Shippings");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Galleries");

                    b.Navigation("InputWarehouses");

                    b.Navigation("OrderDetails");

                    b.Navigation("Promotions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Promotion", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Role", b =>
                {
                    b.Navigation("Staff");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.Supplier", b =>
                {
                    b.Navigation("InputWarehouses");
                });

            modelBuilder.Entity("Web_banThucPhamSach.Data.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Feedbacks");

                    b.Navigation("NewsletterSubscriptions");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
